---
title: "Src"
author: "Adam Walters"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rio)
library(readxl)
library(openxlsx)
library(tm)
library(wordcloud)
library(colorRamps)

```

```{r}
dat <- import("./data/classNoMiss.xlsx",which = 1)
dict <- import("./data/classNoMiss.xlsx",which = 2)
```


```{r}
colInd <- which(names(dat) %in% c("code","strengths","gains"))

dat2 <- dat[,colInd]
```


```{r}
corpS <- Corpus(VectorSource(dat2$strengths))
corpG <- Corpus(VectorSource(dat2$gains))
```


```{r, eval = FALSE}
inspect(corpS)
inspect(corpG)
```

```{r}
corpS <- tm_map(corpS, content_transformer(tolower))
corpS <- tm_map(corpS, removeNumbers)
corpS <- tm_map(corpS, removePunctuation)
corpS <- tm_map(corpS, stripWhitespace)
corpS <- tm_map(corpS,removeWords,stopwords("english"))
#inspect(corpS)
```

1. There should be 62:
2.
## making tdm with corpS
```{r}
termDocS <- TermDocumentMatrix(corpS)
termDocS

inspect(termDocS)
```

3. I don't know what to notice
```{r}
class(termDocS)
termDocSM <- as.matrix(termDocS)
class(termDocSM)
```

4. simple_triplet_matrix

6. and 7.
```{r, eval =FALSE}
termDocSM[,1]
termDocSM[,4]

```

8. 674 terms were found

9. 62 documents

10. "data" appeared 0 times in document 4. I checked manually.

```{r}
docLength <- colSums(termDocSM)
summary(docLength)

termUsage <- rowSums(termDocSM)
summary(termUsage)
```

15. The average length of a document is 25.34 words
```{r}
hist(termUsage)
```

```{r}
dictTerms <- rownames(termDocSM)
dictTerms[termUsage == max(termUsage)]
```


```{r}
termS <- sort(rowSums(termDocSM),decreasing=TRUE)
termS2 <- data.frame(word = names(termS),freq=termS)
head(termS2)
plot(termS2$freq,xlab = "Word Index", ylab = "Frequency")
                     
                                  
```

```{r, warning = FALSE}
#wordcloud(termS2$word,termS2$freq)

#wordcloud(termS2$word,termS2$freq,scale = c(3,0.5))

#wordcloud(termS2$word,termS2$freq,scale = c(2,0.5),
          #min.freq = 1)
wordcloud(termS2$word,termS2$freq,scale = c(2,0.5),
          min.freq = 2)
wordcloud(termS2$word,termS2$freq,scale = c(2,0.5),
          min.freq = 2, rot.per = 0.5)
cols <- rainbow(length(termS2$word))

wordcloud(termS2$word,termS2$freq,scale = c(2,0.5),
          min.freq = 2, rot.per = 0.5, colors = cols,
          random.color = FALSE, ordered.colors = TRUE,
          random.order = FALSE)
```

```{r,warning = FALSE}
numTermsGet2 <- sum(termS2$freq > 1)

cols2 <- blue2green2red(numTermsGet2)

wordcloud(termS2$word[termS2$freq >1],
          termS2$freq[termS2$freq >1]
          ,scale = c(2,0.5),
          min.freq = 2, rot.per = 0.5, colors = cols2,
          random.color = FALSE, ordered.colors = TRUE,
          random.order = FALSE)
```

