---
title: "TFIDF part 2"
author: "Adam Walters"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE}
library(rio)
library(readxl)
library(openxlsx)
library(tm)
library(wordcloud)
library(SnowballC)
library(RColorBrewer)
library(tidyverse)
library(MASS)
```

```{r}
dat <- import("./data/classNoMiss.xlsx",which = 1)
dict <- import("./data/classNoMiss.xlsx",which = 2)
```

```{r}
strNA <- is.na(dat$strengths)
gnsNA <- is.na(dat$gains)
eitherNA <- strNA == TRUE | gnsNA == TRUE
```

```{r}
indCol <- which(names(dat) %in% c("strengths", "gains"))
dat[eitherNA,indCol]
sum(eitherNA)
```

2.
```{r}
dat2 <- dat[eitherNA == FALSE,]
```

3.
```{r}
corpG <- Corpus(VectorSource(dat2$gains))

inspect(corpG[1:4])
```

```{r, warning = FALSE}
corpG <- tm_map(corpG,content_transformer(tolower))
corpG <- tm_map(corpG,removeNumbers)
corpG <- tm_map(corpG,removeWords,stopwords("english"))
corpG <- tm_map(corpG,removePunctuation)
corpG <- tm_map(corpG, stripWhitespace)
```
4. and 5.
```{r, warning = FALSE}
corpG <- tm_map(corpG,removeWords, c("gain", "gains"))
corpG <- tm_map(corpG,stemDocument)

inspect(corpG[1:4])
```
6. and 7.
```{r}
tdG <- TermDocumentMatrix(corpG)
inspect(tdG)

class(tdG)

tdGM <- as.matrix(tdG)
class(tdGM)

tdGM[1:8,1:4]
```

8.
```{r}
termG <- rowSums(tdGM)
termG <- sort(termG, decreasing = TRUE)
termG2 <- data.frame(word = names(termG),freq = termG)
head(termG2)
```


# Part 2
1.
```{r}
plot(termG2$freq,xlab = "word index", ylab = "Frequency")
```

2.
```{r}
wordcloud(termG2$word,termG2$freq,scale = c(2,0.5))
```

3.
```{r}
numTermsGte2 <- sum(termG2$freq > 1)
cols <- rainbow(numTermsGte2)
plot(termG2$freq[termG2$freq > 1], xlab = "Word index", ylab = "Frequency")

wordcloud(termG2$word[termG2$freq >1], termG2$freq[termG2$freq > 1],scale = c(2,0.5), min.freq = 2, rot.per = .5,colors = cols, random.color = FALSE, ordered.colors = TRUE)
```


4. 

5.

6.
```{r}
tdGM[1:4,1:6]
tfidf <- TermDocumentMatrix(corpG, control = list(weighting = function(x) {weightTfIdf(x)}))
tfidf <- as.matrix(tfidf)
tfidf[1:4,1:6]
```

8.
```{r}
tfV <- as.vector(tdGM)
tfidfV <- as.vector(tfidf)
plot(tfV,tfidfV,xlab = "TF", ylab = "TF-IDF")
```


13.
```{r, warning = FALSE}
tfidfByWords <-rowSums(tfidf)
wordcloud(rownames(tfidf),tfidfByWords,scale = c(2,0.5))
```


12. 
```{r}
summary(tfidfByWords)
```



14
```{r}
wordcloud(rownames(tfidf),tfidfByWords,scale = c(2,0.5), min.freq = 0.75)
```

16.
```{r}
orderWords <- order(tfidfByWords, decreasing = TRUE)
tfidfOrder <- tfidf[orderWords,]
rownames(tfidfOrder)[1:10]


```

17.
```{r}
tfidfTr <- t(tfidfOrder)
boxplot(tfidfTr[,1:10],cex = 0.5)
```

```{r}
dim(tfidfTr)

```

24.
```{r}
studCodes = dat2$code
distdat <- dist(tfidfTr)

fit <- cmdscale(distdat, k = 2)
plot(fit, pch = 16, xlab = "Coordinate 1 ", ylab = "Coordinate 2")
text(fit +0.02, label = studCodes, cex = 0.7)

```


21.
```{r}
cols <- rainbow(dim(tfidfTr)[[1]])
parcoord(tfidfTr[,1:10],col = cols)
```

