---
title: "Src"
author: "Adam Walters"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, error = FALSE}
library(tidyverse)
library(imager)
library(readxl)
library(wesanderson)
library(RColorBrewer)
library(MASS)
```

```{r}
dat<- read.csv("~/Data Science/R/bob-ross-analysis-AdamWalters1/data/ImageData.csv")
```

1.
```{r}

feature_counts <- rowSums(dat[, -c(1:2)])


barplot(feature_counts, main = "Number of Features Seen", 
        xlab = "Painting", ylab = "Number of Features")

```

2.
```{r}
# top 5 paintings with most features

total_features <- rowSums(dat[, -c(1:2)])


top <- order(total_features, decreasing = TRUE)[1:5]

#getting names
top_paintings_names <- dat[top, 2]
top_paintings_names

```

3.
```{r}

within_cluster_variance <- c()

for (i in 1:10) {
  km <- kmeans(dat[, -c(1:2)], centers = i)
  within_cluster_variance[i] <- km$tot.withinss
}

#elbow plot
plot(1:10, within_cluster_variance, 
     main = "Elbow Plot",
     xlab = "Number of Clusters", ylab = "Within-cluster Var")

```

4. and 5.
```{r}
# k-means
k <- 3
km <- kmeans(dat[, -c(1:2)], centers = k, nstart = 20)

cols <- rainbow(k)
parcoord(km$centers, col = 1:k, lty = 1)
legend("topright",horiz = FALSE, legend=as.character(1:k),col=cols,
       lty=rep(1,k),lwd=2,cex=.5,bty="n",ncol=2,title="cluster")

```

6.
```{r}
#mds
mds_coords <- cmdscale(dist(dat[, -c(1:2)], method = "binary"))

cols <- rainbow(k)
plot(mds_coords, col = cols[km$cluster], pch = 16, main = "MDS Plot with Clusters")
legend("topright", legend = unique(km$cluster), col = cols[km$cluster], pch = 16, title = "Cluster")

```



7.

```{r}
dat$cluster <- km$cluster
newDat <- dat[, c("OCEAN", "LAKE", "RIVER", "cluster")]

# I had help from chatgpt figuring out how to do this part
average_values <- aggregate(. ~ cluster, data = newDat, FUN = mean)
average_values_long <- reshape2::melt(average_values, id.vars = "cluster")


barplot(average_values_long$value, 
        beside = TRUE, 
        names.arg = paste("Cluster", average_values_long$cluster),
        legend.text = unique(average_values_long$variable),
        xlab = "Cluster", ylab = "Average Value",
        main = "Average of OCEAN, LAKE, and RIVER per image by Cluster",
        col = c("blue", "green", "lightblue")) # Adjust colors as needed

```

